# Generated by Django 2.2.1 on 2019-05-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_date', models.DateField(blank=True, verbose_name='sign date')),
                ('effect_date', models.DateField(blank=True, default='1992-08-08', verbose_name='effect date')),
                ('amount', models.CharField(blank=True, max_length=125, verbose_name='contract amount')),
                ('rent', models.CharField(blank=True, max_length=125, verbose_name='contract rentmoney')),
                ('comment', models.TextField(blank=True, default='', verbose_name='contract comment')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12, verbose_name='Merchant Name')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Merchant Phone')),
                ('wechat', models.CharField(blank=True, max_length=12, verbose_name='Merchant wechat')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=12, verbose_name='Store Name')),
                ('address', models.CharField(blank=True, max_length=12, verbose_name='Store address')),
                ('province', models.CharField(blank=True, max_length=12, verbose_name='province')),
                ('city', models.CharField(blank=True, max_length=12, verbose_name='city')),
                ('area', models.CharField(blank=True, max_length=12, verbose_name='area')),
            ],
        ),
        migrations.CreateModel(
            name='RentBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('actual_date', models.DateField(blank=True, default='1992-08-08')),
                ('real_date', models.DateField(blank=True, default='1992-08-08')),
                ('periods', models.CharField(blank=True, default='', max_length=125)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentbillls', to='estatebusiness.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='merchant',
            field=models.ManyToManyField(related_name='Merchant', to='estatebusiness.Merchant', verbose_name='contract merchant'),
        ),
        migrations.AddField(
            model_name='contract',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='estatebusiness.Store', verbose_name=' contract Store'),
        ),
    ]
