# Generated by Django 2.2.1 on 2019-05-08 06:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Merchant uuid')),
                ('name', models.CharField(max_length=12, verbose_name='Merchant Name')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Merchant Phone')),
                ('wechat', models.CharField(blank=True, max_length=12, verbose_name='Merchant wechat')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=12, verbose_name='Store address')),
                ('province', models.CharField(blank=True, max_length=12, verbose_name='province')),
                ('city', models.CharField(blank=True, max_length=12, verbose_name='city')),
                ('area', models.CharField(blank=True, max_length=12, verbose_name='area')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sign_date', models.DateField(blank=True, verbose_name='sign date')),
                ('effect_date', models.DateField(blank=True, default='1992-08-08', verbose_name='effect date')),
                ('amount', models.CharField(blank=True, max_length=125, verbose_name='contract amount')),
                ('rent', models.CharField(blank=True, max_length=125, verbose_name='contract rentmoney')),
                ('comment', models.TextField(blank=True, verbose_name='contract comment')),
                ('merchant', models.ManyToManyField(related_name='Merchant', to='estatebusiness.Merchant', verbose_name='contract merchant')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estatebusiness.Store', verbose_name=' contract Store')),
            ],
        ),
    ]
