# Generated by Django 2.2.1 on 2019-05-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estatebusiness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='estatebusiness.Store', verbose_name=' contract Store'),
        ),
    ]
