# Generated by Django 2.2.1 on 2019-05-08 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estatebusiness', '0002_auto_20190508_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='contract agent '),
        ),
    ]
