# Generated by Django 2.2.1 on 2019-05-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatebusiness', '0003_contract_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='agent',
            new_name='user',
        ),
    ]
