# Generated by Django 2.2.1 on 2019-05-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatebusiness', '0004_auto_20190508_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=12, verbose_name='Store Name'),
        ),
    ]
