# Generated by Django 2.2.1 on 2019-05-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatebusiness', '0005_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
